#: include gamebutton.kv

<PlaneRow>:
    cols: 12
    Label:
        color: 0,0,0
        text: str(self.parent.number)
    GameButton:
        id: 1
    GameButton:
        id: 2
    GameButton:
        id: 3
    GameButton:
        id: 4
    GameButton:
        id: 5
    GameButton:
        id: 6
    GameButton:
        id: 7
    GameButton:
        id: 8
    GameButton:
        id: 9
    GameButton:
        id: 10
    Label:
        color: 0,0,0
        text: ""